<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Welcome to your journal!</title>
</head>
<body>

<template id="allEntriesTemplate">
  <h2>Dina tidigare inlägg</h2>
  <div id="loginForm">
    
  </div>
</template>

<div class="container">
  <header>
    <h1> <?= $title ?> </h1>
  </header>
</div>

    <script type="text/javascript" src="loggedin.js"></script>
</body>
</html>